name: frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  json_annotation: ^4.8.1
  get_storage: ^2.0.3
  intl: ^0.18.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  get: ^4.6.5
  google_fonts: ^6.1.0
dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
